# File contains the conda environment specifications for batch scoring environment
# The dependencies specified in the file will be automatically provisioned for managed runs.

# These dependencies are used to create the environment used by the batch score 
# pipeline step
name: diabetes_regression_scoring_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.27.*
      
      # Scoring deps
      - scikit-learn
      - pandas
