# configuration file for the containers to be launched
entryScript: score.py
runtime: python
condaFile: ../conda_dependencies.yml
extraDockerfileSteps:
schemaFile:
sourceDirectory:
enableGpu: False
baseImage:
baseImageRegistry: